export default [
    {
        name:'悬浮效果',
        path:'/animation',
    },
    {
        name:'hover效果',
        path:'/hover',
    },
    {
        name:'透视效果',
        path:'/perspective',
    },
    {
        name:'参考与改造',
        path:'/reference',
    },
    {
        name:'导航栏与菜单栏',
        path:'/navigation',
    },
]
